### ISSUE TITLE
Selected Photo Properties: Can't enter info into Caption Description

### ISSUE THREAD

**Issue by RDmitchell** [buechk/calscape-photo-import#12]
I added 2 photos to the collection, and now am using Set Properties to add more information about them.

I have the first photo selected, and could add a Caption Title, but when I click in the Caption Description box, and type, nothing happens. 

![image](https://github.com/buechk/calscape-photo-import/assets/6314950/c099498a-7bcf-47cc-8da5-79dd576e0ac2)

**Comment by RDmitchell** [comment]
The same is true when I try to enter text into the Copyright Notice section -- I type but nothing happens
![image](https://github.com/buechk/calscape-photo-import/assets/6314950/8a1c9969-01af-4bfd-b506-b5d7fa4be923)

**Comment by RDmitchell** [comment]
hmmm, but once I move off the first photo and then onto the 2nd photo, I can enter data into both those fields. 

And then if I go back to the first photo, I can add data into that field also. 

Maybe it's some sort of initialization issue? 

Or it may not be reproducible :<

**Comment by buechk** [comment]
I think it's a timing and initialization issue with toggling selection. When you select a thumbnail, the fields are initialized for that thumbnail, which includes enabling the fields and populating them. Maya also reported this and I've seen it too. I will investigate a fix.

**Comment by buechk** [comment]
Kristy will look into fix.

update: fixed in build 1.0.0.0002

**Comment by RDmitchell** [comment]
Tested: 1.0.0.0005

Fixed !!
