### ISSUE TITLE
Sort and Save: I don't quite understand the workflow

### ISSUE THREAD

**Issue by RDmitchell** [buechk/calscape-photo-import#15]
I don't quite understand the workflow here, possibly because we don't have access to the existing Calscape photos. 

However, the "help" message appears after I have moved my 2 photos over to the right. 

Seems like it would be more useful to be able to see it before I move them. 

And I don't understand what is meant by "select an existing collection"
![image](https://github.com/buechk/calscape-photo-import/assets/6314950/3b86412a-6397-4504-af02-bf2e762581d4)

**Comment by buechk** [comment]
Kristy: In Collection thumbnail grid, use different placeholder text depending on context.

**Comment by RDmitchell** [comment]
Version tested: 1.0.0.0005

I was able to use the Sort and Save function to review collections, add thumbnails from collections, etc.

**Comment by RDmitchell** [comment]
Version tested: 1.0.0.0005

I was able to use the Sort and Save function to review collections, add thumbnails from collections, etc.
