### ISSUE TITLE
Set Properties: Keywords not saved

### ISSUE THREAD

**Issue by RDmitchell** [buechk/calscape-photo-import#3]
In the Set Properties screen, the Keywords are not saved after entering them and moving to the next photo. 

All the other entries are saved under the same circumstances.

**Comment by buechk** [comment]
Kristy will implement autosave if the user types in a keyword then selects another thumbnail without first clicking Add.

**Comment by buechk** [comment]
Fixed and deployed to http://54.183.219.207/photomagic/. Ready for validation.

**Comment by RDmitchell** [comment]
Tested and fixed !
