### ISSUE TITLE
Set Properties: Somehow the date / time got set from an imported file

### ISSUE THREAD

**Issue by RDmitchell** [buechk/calscape-photo-import#4]
Not sure how this happened, but I was editing the properties (Set Properties) and at some point I did something so that only the Caption Description was editable, and then the Photo Date was automatically filled out, presumably from the photo details (I imported this photo from a file, not from Flickr). 

I then clicked again on the photo itself, and all the fields then became editable. 

This is probably impossible to reproduce, but thought I would at least record the behavior. If it happens again I will try to pay more attention to what I did. 
![image](https://github.com/buechk/calscape-photo-import/assets/6314950/0aefea9e-81f0-45e0-9456-b01a79898f42)

**Comment by buechk** [comment]
Robin will investigate whether this is consistent with the EXIF data DateTimeOriginal property being set on the source jpeg file.

**Comment by buechk** [comment]
Also, the issue Robin describes in which, only the Caption description was editable was a bug. It was fixed. Please verify that this does not occur any more as well.
