### ISSUE TITLE
Submit popup doesn't go away

### ISSUE THREAD

**Issue by RDmitchell** [buechk/calscape-photo-import#5]
After submitting a collection, this popup appears
![image](https://github.com/buechk/calscape-photo-import/assets/6314950/1b6d0d62-840c-4d90-8b1f-424c2fe4c93c)

I then went to put together a new collection, and that popup didn't go away. 

I added photos to the new collection, and then tried to Set Properties, but the popup was still there, and was interfering somewhat with editing. 

Seems like that popup should go away once the user moved off the Submit page ??

**Comment by buechk** [comment]
Kristy will fix this. The message will be removed when the user selects another menu option.

**Comment by buechk** [comment]
Fixed and deployed to http://54.183.219.207/photomagic/. Ready for validation.

**Comment by RDmitchell** [comment]
Tested and fixed !!
